version: '3'

services:
  mysql:  
    image: "mysql"
    volumes:
      #- "./schema.sql:/var/lib/mysqldump.sql"
      - "./mysqldump.sql:/var/lib/mysqldump.sql"
    command: "mysqld"
    environment:
      MYSQL_DATABASE: irc
      MYSQL_USER: irc
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
  
  ircd:  
    image: "ghcr.io/yude/inspircd:master"
  #  entrypoint: /bin/sleep inf
    ports:
      - 6667:6667
      - 8080:8080
  #  volumes:
  #    - ./:/opt/inspircd
  #    - ./conf.d/:/inspircd/conf.d/
  #    - ./inspircd.conf:/inspircd/conf/inspircd.conf
    environment:
      MYSQL_HOST: inspircd_mysql_1
      MYSQL_DATABASE: irc
      MYSQL_USER: irc
      MYSQL_PASSWORD: password
      INSPIRCD_SERVER_NAME: "irc.localhost"
      INSPIRCD_SERVER_DESCRIPTION: "Test Network"
      INSPIRCD_NETWORK: "Test Network"
      INSPIRCD_ADMIN_NAME: "Test Network Support"
      INSPIRCD_ADMIN_NICK: "support"
      INSPIRCD_ADMIN_EMAIL: "support@localhost"
      INSPIRCD_LINK_NAME: "anope.localhost"                                                                                                                                                                    
      INSPIRCD_LINK_PORT: "7000"
      INSPIRCD_LINK_SEND_PASS: "secret"
      INSPIRCD_LINK_RECV_PASS: "secret"
      INSPIRCD_CGIHOST_WEBIRC_PASSWORD: "secret"
      INSPIRCD_CLOAK_KEY: "something-very-secret"
      INSPIRCD_STATS_USERNAME: "stats"
      INSPIRCD_STATS_PASSWORD: "secret"
  anope:  
    image: "ghcr.io/yude/anope"
  #  entrypoint: /bin/sleep inf
    ports:
      - 8081:8081
  #  volumes:
  #    - ../anope:/opt/anope
    environment:
      MYSQL_HOST: inspircd_mysql_1
      MYSQL_DATABASE: irc
      MYSQL_USER: irc
      MYSQL_PASSWORD: password
      MYSQL_PREFIX: anope_
      ANOPE_GEOIP_DATABASE: country
      ANOPE_ADMIN_EMAIL: "support@localhost"
      ANOPE_UPLINK_HOST: "inspircd_ircd_1"
      ANOPE_UPLINK_PORT: "7000"
      ANOPE_UPLINK_PASSWORD: "secret"
      ANOPE_SERVERINFO_NAME: "anope.localhost"
      ANOPE_SALT: "secret"
      ANOPE_URL: "http://localhost/register/"
  
  
